# Generated by Django 2.2.5 on 2019-09-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbióra lokalna')], default=1)),
                ('categories', models.ManyToManyField(to='oddam.Category')),
            ],
        ),
    ]
