# Generated by Django 2.2.5 on 2019-09-23 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oddam', '0002_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(related_name='institution_category', to='oddam.Category'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField(max_length=9)),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.IntegerField()),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.CharField(max_length=256)),
                ('categories', models.ManyToManyField(related_name='donation_category', to='oddam.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_institution', to='oddam.Institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
