# Generated by Django 2.2.5 on 2019-09-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam', '0003_auto_20190923_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
