# Generated by Django 2.2.5 on 2019-09-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam', '0004_auto_20190923_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
